# Generated by Django 5.2.4 on 2025-09-01 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ll', max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('متجر إلكتروني', 'متجر إلكتروني'), ('مدونة', 'مدونة'), ('منصة تعليمية', 'منصة تعليمية'), ('خدمات', 'خدمات')], default='خدمات', max_length=100)),
                ('gimpse', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=375)),
            ],
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('features', models.JSONField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, null=True)),
                ('plan', models.ManyToManyField(to='home.plan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.service')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.plan')),
                ('description', models.ManyToManyField(to='home.pricingfeature')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.service')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.project')),
            ],
            options={
                'unique_together': {('project', 'visitor_id')},
            },
        ),
        migrations.CreateModel(
            name='SavedProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
            options={
                'unique_together': {('project', 'visitor_id')},
            },
        ),
    ]
