# Generated by Django 5.2.4 on 2025-09-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='plan',
        ),
    ]
