# Generated by Django 5.2.4 on 2025-09-02 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_pricing_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.plan'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.service'),
        ),
    ]
