# Generated by Django 5.2.4 on 2025-09-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pricing_plan_alter_pricing_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='plan',
        ),
    ]
