# Generated by Django 5.2.4 on 2025-09-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_pricing_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='services',
        ),
    ]
