# Generated by Django 5.2.4 on 2025-09-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_pricing_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='description',
        ),
    ]
