# Generated by Django 5.2.4 on 2025-09-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_pricing_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
