# Generated by Django 5.2.4 on 2025-08-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_service_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
