# Generated by Django 5.2.4 on 2025-09-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.ManyToManyField(to='home.pricingfeature')),
                ('plan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.plan')),
                ('services', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.service')),
            ],
        ),
    ]
