# Generated by Django 5.2.4 on 2025-09-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_pricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='plan',
        ),
        migrations.AlterField(
            model_name='pricing',
            name='description',
            field=models.ManyToManyField(default=1, to='home.pricingfeature'),
        ),
    ]
