# Generated by Django 5.2.4 on 2025-09-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_pricing_plan_alter_pricing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.plan'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='description',
            field=models.ManyToManyField(to='home.pricingfeature'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.service'),
        ),
    ]
