# Generated by Django 5.2.4 on 2025-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
