# Generated by Django 5.2.4 on 2025-09-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_pricing_plan_alter_pricing_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
