# Generated by Django 5.2.4 on 2025-08-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_image_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageTitle',
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
