# Generated by Django 5.2.4 on 2025-08-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_image_imagetitle_alter_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(default='خدمات', max_length=100),
        ),
    ]
