# Generated by Django 5.2.4 on 2025-08-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('متجر إلكتروني', 'متجر إلكتروني'), ('مدونة', 'مدونة'), ('منصة تعليمية', 'منصة تعليمية'), ('خدمات', 'خدمات')], default='خدمات', max_length=100),
        ),
        migrations.CreateModel(
            name='Favorits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
            options={
                'unique_together': {('project', 'visitor_id')},
            },
        ),
    ]
