# Generated by Django 5.2.4 on 2025-08-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_project_type_favorits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorits',
            new_name='Favorites',
        ),
    ]
