# Generated by Django 5.2.4 on 2025-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_favorits_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
