# Generated by Django 5.2.4 on 2025-08-09 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_favorites_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_id', models.CharField(max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
            options={
                'unique_together': {('project', 'visitor_id')},
            },
        ),
    ]
