# Generated by Django 5.2.4 on 2025-08-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_project_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favourites',
        ),
    ]
