# Generated by Django 5.2.4 on 2025-08-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
