# Generated by Django 5.2.4 on 2025-08-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_pricing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title',
            field=models.CharField(default='ll', max_length=100),
        ),
    ]
